# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Lint and Build

on:
  push:
    branches: ['master']
  workflow_dispatch: # Manual trigger deploy from local by command `gh workflow run`

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Test build docker image
        run: docker build . -t flare
      - name: Stop current running docker container
        run: docker stop flare || true
      - name: Run docker container
        run: > 
          docker run -d 
          -e GOOGLE_ID=${{ secrets.GOOGLE_ID }} 
          -e GOOGLE_SECRET=${{ secrets.GOOGLE_SECRET }} 
          -e AUTH_SECRET=${{ secrets.AUTH_SECRET }} 
          -e AUTH_TRUST_HOST=${{ secrets.AUTH_TRUST_HOST }} 
          --name flare 
          -p 4173:4173 flare
      - name: Cleanup dangling docker
        run: docker image prune -f && docker volume prune -f
