# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Lint and Build

on:
  push:
    branches: ['master']
  workflow_dispatch: # Manual trigger deploy from local by command `gh workflow run`

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Test Install node dependencies
        run: pnpm i
      - name: Test ESLint
        run: pnpm lint
      - name: Test build package for deployment
        run: pnpm build
      - name: copy build files to deploy folder
        run: cp -r ./build/* ${{ DEPLOY_PATH }}
      - name: Run Server
        run: cd ${{ DEPLOY_PATH }} && pnpm execute
